feat(mfa): #WB-1608, track id of sent sms
opendigitaleducation/entcore pull request #320
Opened 2023-02-20 15:56 UTC by juniorode

Afin de pouvoir suivre la bonne réception des SMS et de qualifier les problèmes de réception, la solution suivante a été mise en place :
- récupérer les ids des sms envoyés par le provider
- enregistrer ces ids dans les tables d'événements

2023-02-22 07:31 UTC, dboissin requested changes

2023-02-22 07:31 UTC, dboissin commented on auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
> +            sms = Sms.getFactory().newInstance(null );
???

2023-02-22 07:31 UTC, dboissin commented on auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
> +import fr.wseduc.webutils.Server;
Il faudrait mettre des règles pour que tous les ide ordonnent les imports de la même manière...

2023-02-22 07:31 UTC, dboissin commented on auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
> +                    final long[] sentSmdIds = sendSmsResult.getIds();
Pas forcement un long en fonction du provider.

2023-02-22 07:31 UTC, dboissin commented on common/src/main/java/org/entcore/common/sms/Sms.java
> +	public static final String EVENT = "SMS";
Classe à déplacer dans web-utils

2023-02-22 07:31 UTC, dboissin commented on common/src/main/java/org/entcore/common/sms/Sms.java
> +						final SmsSendingReport report = event.body().getJsonObject("data").mapTo(SmsSendingReport.class);
Tu n'as pas un risque d'exception ici ? Si jackson n'arrive pas à désérialiser.

2023-02-22 07:31 UTC, dboissin commented on common/src/main/java/org/entcore/common/sms/Sms.java
> +						if (module != null && !module.isEmpty()) {
Tu as une méthode static isNotEmpty pour faire ça.

2023-02-22 07:31 UTC, dboissin commented on common/src/main/java/org/entcore/common/sms/SmsSendingReport.java
> +    private final long[] ids;
Pas forcément un long.

2023-02-22 07:31 UTC, dboissin commented on common/src/main/java/org/entcore/common/sms/SmsSendingReport.java
> +public class SmsSendingReport {
À déplacer dans web-utils

2023-02-22 14:53 UTC, juniorode commented on auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
> +            sms = Sms.getFactory().newInstance(null );
J'ai supposé que les `???` était pour le passage d'un unique paramètre `null`.
En refactorant un peu cette méthode n'est plus appelée avec juste `null` et la javadoc explique ce qui se passe sous le capot

2023-02-22 14:56 UTC, juniorode commented on auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
> +import fr.wseduc.webutils.Server;
C'est sur ma liste de choses à faire mais il faut que je fasse 2 fichiers de conf : 1 pour IDEA et 1 pour VSCode

2023-02-22 14:58 UTC, juniorode commented on common/src/main/java/org/entcore/common/sms/Sms.java
> +	public static final String EVENT = "SMS";
Classe déplacée

2023-02-22 15:01 UTC, juniorode commented on common/src/main/java/org/entcore/common/sms/Sms.java
> +						if (module != null && !module.isEmpty()) {
Changé

2023-02-22 15:01 UTC, juniorode commented on common/src/main/java/org/entcore/common/sms/SmsSendingReport.java
> +    private final long[] ids;
Changé

2023-02-22 15:01 UTC, juniorode commented on common/src/main/java/org/entcore/common/sms/SmsSendingReport.java
> +public class SmsSendingReport {
Déplacée

2023-02-22 15:06 UTC, juniorode commented on common/src/main/java/org/entcore/common/sms/Sms.java
> +						final SmsSendingReport report = event.body().getJsonObject("data").mapTo(SmsSendingReport.class);
J'ai capté l'erreur, je la loggue et je `fail` la _Promise_ le cas échéant

2023-02-23 07:27 UTC, dboissin approved these changes

2023-02-23 07:27 UTC, dboissin commented on common/src/main/java/org/entcore/common/validation/StringValidation.java
> -	public static String obfuscateMobile(String mobile){
Audacieux.
Tu as vérifié que ce n'était pas utilisé en dehors d'entcore ?
Remarque, on le verra vite si des modules ne compile plus.

2023-02-23 07:28 UTC, merged