[ODE] WB-1700 cipher codes for sms/email validation, and MFA, in DB
opendigitaleducation/entcore pull request #341
Opened 2023-04-12 09:45 UTC by jcbe-ode

# Description

Les codes de validation des données ou de MFA ne devraient pas être stockés en clair dans la base de données, même s'ils sont temporaires.
L'implémentation proposée ici consiste à supporter un nouveau paramètre (clé de cryptage) et à l'utiliser lors de l'écriture / lecture d'un code en BDD.

## Fixes

WB-1700

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [X] auth
- [ ] cas
- [X] common
- [ ] communication
- [ ] conversation
- [ ] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

Validation d'un numéro mobile + MFA, en vérifiant manuellement les codes reçus pas SMS et leurs cryptages dans Neo4j.

# Reminder

- Security flaws (bros before security holes)
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [X] All done ! :smiley:

2023-04-12 11:40 UTC, juniorode requested changes

2023-04-12 11:40 UTC, juniorode commented on common/src/main/java/org/entcore/common/sql/SqlResult.java
> +	public static <T> List<T> sqlArrayToList(JsonArray array, Class<T> clazz) {
Comme c'est une méthode publique il faudrait mettre de la javadoc.
Au début je pensais que la méthode convertissait juste un JsonArray en String et j'allais laisser un message disant qu'il y avait plus facile pour le faire mais là de ce que je comprends du code elle s'attend à un "format" bien particulier des éléments de `array`. ça il faudrait l'expliquer pour que ce soit réutilisable. Et si en fin de compte on voit que le cas d'utilisation est bcp trop précis on pourrait passer la méthode en private.

2023-04-12 11:40 UTC, juniorode commented on common/src/main/java/org/entcore/common/sql/SqlResult.java
> +				if (item.size() == 2) {
C'est cette vérif là qui me fait penser que le cas d'utilisation est bien précis.

2023-04-12 11:40 UTC, juniorode commented on common/src/main/java/org/entcore/common/datavalidation/impl/AbstractDataValidationService.java
> +		if( encryptKey != null
Ce genre de vérification il vaut mieux le faire à l'instanciation du service pour que le verticle ne démarre pas et que l'on ait une erreur débuggable plutôt que ça pète silencieusement plus tard [(failfast)](https://www.martinfowler.com/ieeeSoftware/failFast.pdf)

2023-04-12 12:32 UTC, jcbe-ode commented
Petite erreur lors de la création de la PR, désolé.
Je la modifie car les commentaires ne concernent pas le fix, en pratique.

2023-04-12 14:34 UTC, juniorode commented on common/src/main/java/org/entcore/common/datavalidation/impl/AbstractDataValidationService.java
> +		if( encryptKey != null
Ok pour le contrôle en amont, ceci dit du coup celui-ci devient redondant

2023-04-13 06:49 UTC, juniorode approved these changes

2023-04-13 06:49 UTC, merged