Fix: #WB-2026, Change display to firstname for welcome key i18n
opendigitaleducation/entcore pull request #398
Opened 2023-10-19 13:58 UTC by Romu-C

# Description

Change display for welcome key I18n for displayName to firstname

## Fixes

https://edifice-community.atlassian.net/browse/WB-2026

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [x] Bug fix (PATCH)
- [ ] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [x] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [ ] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

1. Describe here the tests you performed
2. Step by step
3. With expected results

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [x] All done ! :smiley:

2023-10-20 07:52 UTC, ccreusat approved these changes

2023-10-20 08:04 UTC, jcbe-ode commented
Sur entcore et infra-front, je préfèrerais que le formatage auto soit désactivé.
- on l'activera dans entcore lors de la migration front. 
- infra-front restera en l'état et sera dépréciée.

2023-10-20 08:05 UTC, jcbe-ode requested changes
Sur entcore et infra-front, je préfèrerais que le formatage auto soit désactivé.

    on l'activera dans entcore lors de la migration front.
    infra-front restera en l'état et sera dépréciée.

2023-10-31 09:44 UTC, Romu-C commented
> Sur entcore et infra-front, je préfèrerais que le formatage auto soit désactivé.
> 
> ```
> on l'activera dans entcore lors de la migration front.
> infra-front restera en l'état et sera dépréciée.
> ```

Je viens de retirer le formatage

2023-11-10 14:45 UTC, merged