Feat: #WB-2247 Move LOOL aciton in Workspace to the title bar
opendigitaleducation/entcore pull request #402
Opened 2023-10-30 14:56 UTC by Romu-C

# Description

Move LOOL action (create document) from under the folder tree to the title bar with the import button

## Fixes

[WB-2247](https://edifice-community.atlassian.net/browse/WB-2247)

## Type of change

Please check options that are relevant.

- [x] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [ ] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [x] workspace

## Tests

1. Go to workspace app and check the place of the button "Create document"

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [x] All done ! :smiley:

2023-10-30 16:32 UTC, ccreusat requested changes

2023-10-30 16:32 UTC, ccreusat commented on workspace/src/main/resources/view-src/workspace.html
> -		var ENABLE_LOOL= {{enableLool}};
variable retirée ??

2023-10-30 16:57 UTC, jcbe-ode commented on workspace/src/main/resources/public/ts/delegates/lool.ts
> +               const data = typeof event.data !== 'object' ? JSON.parse(event.data) : event.data;
```suggestion
               const data = typeof event.data === 'string' ? JSON.parse(event.data) : event.data;
```

2023-10-30 17:01 UTC, jcbe-ode commented on workspace/src/main/resources/public/ts/delegates/lool.ts
> +               const data = typeof event.data !== 'object' ? JSON.parse(event.data) : event.data;
Mais je déconseillerais aujourd'hui toute modification de code qui n'est pas en rapport avec le besoin initial du ticket.
Il faut considérer que ce code source est désormais "legacy", et qu'on va principalement corriger les bugs signalés, avant réécriture des applis front.

2023-10-31 08:36 UTC, Romu-C commented on workspace/src/main/resources/view-src/workspace.html
> -		var ENABLE_LOOL= {{enableLool}};
Erreur de ma part c'était pour tester en local j'ai oublié de la retirer.

2023-10-31 08:37 UTC, Romu-C commented on workspace/src/main/resources/public/ts/delegates/lool.ts
> +               const data = typeof event.data !== 'object' ? JSON.parse(event.data) : event.data;
Ok j'ai juste une erreur qui pop en boucle sur od1 à cause de cette ligne. Je sais pas si ça peut être bloquant.

2023-10-31 13:12 UTC, Romu-C commented on workspace/src/main/resources/public/ts/delegates/lool.ts
> +               const data = typeof event.data !== 'object' ? JSON.parse(event.data) : event.data;
Après discution avec JC j'ai retiré les modification

2023-11-10 11:12 UTC, merged